const AppConstants = {
  Status: {
    OK                   : 200,
    CREATED              : 201,
    BAD_REQUEST          : 400,
    UNAUTHORIZED         : 401,
    NOT_FOUND            : 404,
    INTERNAL_SERVER_ERROR: 500,
  },
  Messages: {
    ERROR_AUTHENTICATION_FAILED: 'Error de autenticación.',
    ERROR_INTERNAL_SERVER      : 'Error interno del servidor.',
    ERROR_CREDENTIALS_REQUIRED : 'Credenciales requeridas.',
    ERROR_MISSING_FIELDS       : 'Campos faltantes.',
    ERROR_INVALID_INPUT        : 'Entrada de datos inválida.',
    ERROR_USER_NOT_FOUND       : 'Usuario no encontrado.',
    ERROR_DATABASE_ERROR       : 'Error de la base de datos.',
    ERROR_USER_ALREADY_EXISTS  : 'El usuario ya existe.',
    ERROR_EMAIL_ALREADY_EXISTS : 'El correo electrónico ya está en uso.',
    ERROR_TOKEN_NOT_PROVIDED   : 'Token no proporcionado.',
    ERROR_TOKEN_INVALID        : 'Token inválido o expirado.',
    ERROR_PASSWORDS_DO_NOT_MATCH: 'Las contraseñas no coinciden.',

    REGISTER_SUCCESS: 'Registro exitoso.',
    LOGIN_SUCCESS   : 'Inicio de sesión exitoso.',
    AUTH_SUCCESS    : 'Autenticación exitosa.',

    USER_LIST_SUCCESS  : 'Lista de usuarios obtenida exitosamente.',
    USER_LIST_FAILED   : 'Error al obtener la lista de usuarios.',
    USER_DETAIL_SUCCESS: 'Detalles del usuario obtenidos exitosamente.',
    USER_DETAIL_FAILED : 'Error al obtener los detalles del usuario.',
    USER_DELETE_SUCCESS: 'Usuario eliminado exitosamente.',
    USER_DELETE_FAILED : 'Error al eliminar el usuario.',

    DOCTOR_LIST_SUCCESS  : 'Lista de doctores obtenida exitosamente.',
    DOCTOR_LIST_FAIL     : 'Error al obtener la lista de doctores.',
    DOCTOR_CREATE_SUCCESS: 'Doctor creado exitosamente.',
    DOCTOR_CREATE_FAIL   : 'Error al crear el doctor.',
    DOCTOR_FETCH_SUCCESS : 'Doctor obtenido exitosamente.',
    DOCTOR_FETCH_FAIL    : 'Error al obtener el doctor.',
    DOCTOR_UPDATE_SUCCESS: 'Doctor actualizado exitosamente.',
    DOCTOR_UPDATE_FAIL   : 'Error al actualizar el doctor.',
    DOCTOR_NOT_FOUND     : 'Doctor no encontrado.',

    PATIENT_LIST_SUCCESS  : 'Lista de pacientes obtenida exitosamente.',
    PATIENT_LIST_FAILED   : 'Error al obtener la lista de pacientes.',
    PATIENT_CREATE_SUCCESS: 'Paciente creado exitosamente.',
    PATIENT_CREATE_FAILED : 'Error al crear el paciente.',
    PATIENT_DETAIL_SUCCESS: 'Detalles del paciente obtenidos exitosamente.',
    PATIENT_DETAIL_FAILED : 'Error al obtener los detalles del paciente.',
    PATIENT_UPDATE_SUCCESS: 'Paciente actualizado exitosamente.',
    PATIENT_UPDATE_FAILED : 'Error al actualizar el paciente.',
    PATIENT_DELETE_SUCCESS: 'Paciente eliminado exitosamente.',
    PATIENT_DELETE_FAILED : 'Error al eliminar el paciente.',
  },

  Roles: {
    ADMIN       : 'admin',
    DOCTOR      : 'doctor',
    PATIENT     : 'patient',
    GUEST       : 'guest',
    RECEPTIONIST: 'receptionist',
    STAFF       : 'staff',
  },

  APP_NAME   : 'MiAplicacionWeb',
  MAX_RETRIES: 3,
};

module.exports = AppConstants;
